### ISSUE TITLE
Window title changing not working on Linux

### ISSUE THREAD

**Issue by kattjevfel** [Wynntils/Wynntils-Legacy#166]
e0a138dd1a29c997adeeac1795a7e2336d2be56b added the feature to set the window title to "Wynncraft", but it doesn't appear to be working, at least on Linux (I have no ability to check on any other OS).

![image](https://i.imgur.com/3LbVi5i.png)

Running Wynntils-DEV build [611](https://ci.wynntils.com/job/Wynntils-DEV/611/), Java 8.u232, KDE Plasma 5.17.4
If this feature is meant to be Windows only, please label it so.

Realised it'd be real smart of me to include some log output, this seems to be of value:
```
[10:45:02] [main/FATAL] [net.minecraft.client.Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_232]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_232]
	at net.minecraft.util.Util.func_181617_a(Util.java:48) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1087) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_232]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_232]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_232]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_232]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.client.gui.GuiBossOverlay.func_184055_a(GuiBossOverlay.java:91) ~[biz.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_184325_a(NetHandlerPlayClient.java:1815) ~[brz.class:?]
	at net.minecraft.network.play.server.SPacketUpdateBossInfo.func_148833_a(SourceFile:126) ~[ik.class:?]
	at net.minecraft.network.play.server.SPacketUpdateBossInfo.func_148833_a(SourceFile:11) ~[ik.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_232]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_232]
	at net.minecraft.util.Util.func_181617_a(Util.java:47) ~[h.class:?]
	... 9 more
```

Full log: [debug.log](https://github.com/Wynntils/Wynntils/files/3982846/debug.log)

**Comment by kattjevfel** [comment]
With a7b2031a91542414119c230d5dd11328088e75e1 it now gets set when I manually change the setting. However, it gets reset to blank (as in no title at all) when leaving server & it doesn't automatically get re-enabled when joining once more.

I'm not sure if I should close this issue and make new ones for the previously mentioned issues.. (as the error doesn't seem related after all, and I'm not sure it really is Linux specific)

**Comment by coehlrich** [comment]
Can you try with a936c52ca09804553a98f10bbd30c91926d20702

**Comment by kattjevfel** [comment]
All good now, no more blank titles and it gets applied when it should. Thanks for the quick fix! :)
