### ISSUE TITLE
First to join a server with uptime variables causes crash

### ISSUE THREAD

**Issue by ryanzhoudev** [Wynntils/Wynntils-Legacy#401]
### Version

CE1401

### Brief Description

If the first player to join a server has info variables with either uptime variable in use, the game will crash as there is no uptime data for that server yet.

### Steps to Reproduce

Be the first to join a server while using %uptime_h% or %uptime_m% in info variables.

### Crash Report

Time: 12/19/21 4:19 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at com.wynntils.modules.utilities.managers.**ServerListManager.getUptimeHours(ServerListManager.java:31)**
	at com.wynntils.modules.utilities.instances.InfoFormatter.lambda$new$58(InfoFormatter.java:435)
	at com.wynntils.modules.utilities.instances.InfoFormatter.doFormat(InfoFormatter.java:480)
	at com.wynntils.modules.utilities.overlays.hud.InfoOverlay.render(InfoOverlay.java:36)
	at com.wynntils.core.framework.FrameworkManager.triggerPreHud(FrameworkManager.java:172)
	at com.wynntils.core.events.ClientEvents.handleFrameworkPreHud(ClientEvents.java:216)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_26_ClientEvents_handleFrameworkPreHud_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:119)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1426)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

### Installed Mods

Wynntils, Optifine, Phosphor

**Comment by manch1915** [comment]
i have this problen, can i solove?
