### ISSUE TITLE
Chat Overlay Crash

### ISSUE THREAD

**Issue by ryanzhoudev** [Wynntils/Wynntils-Legacy#403]
### Version

CE1401

### Brief Description

Game crashed while joining a new world using /pfinder. Not really sure what caused it.

### Steps to Reproduce

Join some world via finding a /pfinder group.

### Crash Report

Time: 12/24/21 3:00 AM
Description: Unexpected error

java.lang.IndexOutOfBoundsException: Index: 8, Size: 8
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at com.wynntils.modules.chat.overlays.ChatOverlay.func_146230_a(ChatOverlay.java:78)
	at net.minecraftforge.client.GuiIngameForge.renderChat(GuiIngameForge.java:827)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:199)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1426)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

### Installed Mods

Wynntils, Phosphor, Optifine

**Comment by kristofbolyai** [comment]
One way I can think of that makes this happen is when `chatSize` gets outdates by the time the for loop finishes. Is that even possible? (Maybe if `getCurrentTab().getCurrentMessages()` gets cleared?)

Maybe, removing `chatSize` and getting the size every time would fix this issue?

Or maybe, `scrollPos` gets updated during the loop somehow? Once again, is that possbile? Since, this happened when player switched worlds, maybe a message from that switch modified the scroll value, making this possible. `ChatOverlay.addLine()` sets scroll value, possibly that is what happened?

```java
    public void drawChat(int updateCounter) {
        if (McIf.mc().gameSettings.chatVisibility != EntityPlayer.EnumChatVisibility.HIDDEN) {
            int chatSize = getCurrentTab().getCurrentMessages().size();

            getCurrentTab().checkNotifications();

            boolean flag = false;

            if (getChatOpen()) flag = true;

            float chatScale = getChatScale();
            int extraY = MathHelper.ceil((float)getChatWidth() / chatScale) + 4;
            GlStateManager.pushMatrix();
            GlStateManager.translate(2.0F, 0.0F, 0.0F);
            GlStateManager.scale(chatScale, chatScale, 1.0F);
            int l = 0;

            for (int i1 = 0; i1 + scrollPos < chatSize && i1 < getLineCount(); ++i1) {
                ChatLine chatline = getCurrentTab().getCurrentMessages().get(i1 + scrollPos);
```
