### ISSUE TITLE
Crafted Gear Viewer Crash

### ISSUE THREAD

**Issue by ryanzhoudev** [Wynntils/Wynntils-Legacy#404]
### Version

CE 1401

### Brief Description

Middle clicking on a player with full crafted gear results in a crash.

### Steps to Reproduce

Middle click on a player with full crafted gear to view.

### Crash Report

```
java.lang.NoClassDefFoundError: com/wynntils/modules/utilities/instances/ContainerGearViewer$1
	at com.wynntils.modules.utilities.overlays.ui.GearViewerUI.<init>(GearViewerUI.java:62)
	at com.wynntils.modules.utilities.overlays.ui.GearViewerUI.openGearViewer(GearViewerUI.java:361)
	at com.wynntils.core.framework.instances.containers.ModuleContainer.lambda$triggerKeyBinding$0(ModuleContainer.java:53)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.wynntils.core.framework.instances.containers.ModuleContainer.triggerKeyBinding(ModuleContainer.java:51)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at com.wynntils.core.framework.FrameworkManager.triggerKeyPress(FrameworkManager.java:243)
	at com.wynntils.core.events.ClientEvents.onTick(ClientEvents.java:232)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_22_ClientEvents_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.wynntils.modules.utilities.instances.ContainerGearViewer$1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 22 more
Caused by: java.lang.NullPointerException
```

### Installed Mods

Wynntils, Optifine, Phosphor

**Comment by kristofbolyai** [comment]
As it's a `java.lang.ClassNotFoundException` could it be some weird error with that build/mod file specifically?

**Comment by ryanzhoudev** [comment]
Root cause is overwriting the wynntils .jar with a different version while Minecraft is running. Not really an issue anymore.
