### ISSUE TITLE
Wynntils just not staring on MultiMc

### ISSUE THREAD

**Issue by ninlego** [Wynntils/Wynntils-Legacy#543]
### Version

1.12.2

### Brief Description

I followed the steps on installing wynntils on MultiMc and it does not start.

MultiMC version: 0.6.16-3431

Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
Exiting with -1
Process exited with code -1 (0xffffffffffffffff).

### Steps to Reproduce

Do the steps on the wynntils website for MultiMc

### Expected Behaviour

Minecraft starts up

### Actual Behaviour

Minecraft does not start up

**Comment by ninlego** [comment]
My bad its just my multimc acting up

**Comment by xcfrg** [comment]
The issue is neither due to MultiMC nor Wynntils, it's because you used a java version above 8 with legacy forge. That isn't supported and will crash.
