### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by EnderNon** [Wynntils/Wynntils-Legacy#654]
### Version

1.14.0

### Brief Description

randomly started crashing on startup. it gets stuck on 12/13, and then crashes. started happening after i closed my game via the X button one time, but now it keeps doing it.

### Steps to Reproduce

1) start mc

### Crash Report

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2023-01-03 15:47:50 GMT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Wynntils (wynntils)
Caused by: java.lang.NullPointerException
    at com.wynntils.modules.map.commands.CommandLocate.getFeatureKey(CommandLocate.java:51)
    at com.wynntils.modules.map.commands.CommandLocate.<init>(CommandLocate.java:31)
    at com.wynntils.modules.map.MapModule.onEnable(MapModule.java:69)
    at com.wynntils.core.framework.FrameworkManager.lambda$startModules$0(FrameworkManager.java:118)
    at java.util.HashMap$Values.forEach(Unknown Source)
    at com.wynntils.core.framework.FrameworkManager.startModules(FrameworkManager.java:118)
    at com.wynntils.ModCore.preInit(ModCore.java:75)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
    at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
    at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_351, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1027992440 bytes (980 MB) / 1325400064 bytes (1264 MB) up to 3817865216 bytes (3641 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G5 13 mods loaded, 13 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                | Version        | Source                                      | Signature                                |
       |:----- |:----------------- |:-------------- |:------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft         | 1.12.2         | minecraft.jar                               | None                                     |
       | LCH   | mcp               | 9.42           | minecraft.jar                               | None                                     |
       | LCH   | FML               | 8.0.99.99      | forge-1.12.2-14.23.5.2859-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge             | 14.23.5.2859   | forge-1.12.2-14.23.5.2859-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | ColorUtility      | 1.0.4          | minecraft.jar                               | None                                     |
       | LCH   | foamfixcore       | 7.7.4          | minecraft.jar                               | None                                     |
       | LCH   | foamfix           | 0.10.14-1.12.2 | foamfix-0.10.14-1.12.2.jar                  | None                                     |
       | LCH   | realFake          | 1.0            | RealFake.jar                                | None                                     |
       | LCH   | vanillafix        | 1.0.10-150     | VanillaFix-1.0.10-150.jar                   | None                                     |
       | LCH   | wynnvp            | 1.2            | VoicesOfWynnMC1.12.2v1.2.jar                | None                                     |
       | LCH   | wi-zoom           | 1.0            | wi-zoom-v1.1-MC1.12.2-release.jar           | None                                     |
       | LCE   | wynntils          | 1.14.0         | Wynntils-MC1.12.2-v1.14.0.jar               | None                                     |
       | LC    | phosphor-lighting | 1.12.2-0.2.7   | phosphor-forge-mc1.12.2-0.2.7-universal.jar | None                                     |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      WiZoomCoreMod (wi-zoom-v1.1-MC1.12.2-release.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
                                        
                                      ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
                                        com.Axeryok.ColorUtility.ColorUtilityTransformer
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 22.11.2.221130' Renderer: 'Radeon RX 570 Series'
  Suspected Mods: Wynntils (wynntils)
  Launched Version: 1.12.2
  LWJGL: 2.9.4
  OpenGL: Radeon RX 570 Series GL version 4.6.0 Compatibility Profile Context 22.11.2.221130, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Wynncraft+Retextured+1.1_for_1.13+.zip (incompatible), Wynnic+Uniques+Compendium-1.0-1.12.2-1.16.zip (incompatible), Wynnic+Vanity+Collection-0.4-1.12.2-1.16.zip (incompatible)
  Current Language: English (United Kingdom)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz

### Installed Mods

Colorutility (there's no way this would conflict), 
Foamfix (+Foamfixcore), 
realfake thingy (personal mod, should not conflict ever)
Vanillafix, 
Voices of Wynn, 
wi-zoom, 
Wynntils, 
phosphor (lighting engine),

**Comment by memecorn** [comment]
have you tried disabling all the mods except wynntils and see if it crashes that way?

**Comment by magicus** [comment]
This crash is on the old 1.12 version ("legacy"). We do not support it anymore, apart from obvious problems that crashes the game for everyone.

If you want to keep using it, I suggest going with @memecorn's suggestion, otherwise my warm recommendation is to switch to the 1.19 version ("artemis").
