### ISSUE TITLE
crash upon pressing esc+1 while in an menu

### ISSUE THREAD

**Issue by EnderNon** [Wynntils/Wynntils-Legacy#658]
### Version

1.14.1 beta 7

### Brief Description

open menu, then press esc, and suddenly press 1 too fast. wynntils then crashes. it's happened multiple times now, what's behind it? supposedly, according to VanillaFix, wynntils is behind it.

### Steps to Reproduce

1) go to gui menu for buying stuff

2) press esc

3) press 1 too quickly at the same time

4) crash

### Crash Report

---- Minecraft Crash Report ----
// My bad.

Time: 2023-01-23 21:26:42 GMT
Description: Updating screen events

java.lang.IndexOutOfBoundsException: Index: 50, Size: 46
    at java.util.ArrayList.rangeCheck(Unknown Source)
    at java.util.ArrayList.get(Unknown Source)
    at net.minecraft.inventory.Container.slotClick(Container.java:356)
    at net.minecraft.client.multiplayer.PlayerControllerMP.windowClick(PlayerControllerMP.java:566)
    at net.minecraft.client.gui.inventory.GuiContainer.handleMouseClick(GuiContainer.java:638)
    at com.wynntils.modules.core.overlays.inventories.ChestReplacer.handleMouseClick(ChestReplacer.java:58)
    at net.minecraft.client.gui.inventory.GuiContainer.checkHotbarKeys(GuiContainer.java:671)
    at net.minecraft.client.gui.inventory.GuiContainer.keyTyped(GuiContainer.java:648)
    at com.wynntils.modules.core.overlays.inventories.ChestReplacer.keyTyped(ChestReplacer.java:88)
    at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:558)
    at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:512)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
    at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176)
    at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186)
    at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144)
    at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected screen --
  Screen name: ~~ERROR~~ NullPointerException: null

-- Affected level --
  Level name: MpServer
  All players: 41 total; [EntityPlayerSP['ender_non'/5053603, l='MpServer', x=1058.49, y=18.00, z=-5154.89], EntityOtherPlayerMP['§'/9472026, l='MpServer', x=1064.05, y=19.00, z=-5152.30], EntityOtherPlayerMP['§'/9467891, l='MpServer', x=1078.88, y=1.14, z=-5164.32], EntityOtherPlayerMP['§'/9471017, l='MpServer', x=1074.65, y=2.53, z=-5166.60], EntityOtherPlayerMP['§'/9470552, l='MpServer', x=1063.84, y=2.86, z=-5168.86], EntityOtherPlayerMP['§'/9474131, l='MpServer', x=1083.30, y=2.24, z=-5127.09], EntityOtherPlayerMP['§'/9481914, l='MpServer', x=1062.50, y=18.00, z=-5126.50], EntityOtherPlayerMP['§'/9494043, l='MpServer', x=1058.50, y=18.00, z=-5121.50], EntityOtherPlayerMP['§'/9468467, l='MpServer', x=1062.99, y=18.00, z=-5137.76], EntityOtherPlayerMP['§'/9494279, l='MpServer', x=1058.50, y=18.00, z=-5119.50], EntityOtherPlayerMP['§'/9467931, l='MpServer', x=1053.00, y=18.00, z=-5169.00], EntityOtherPlayerMP['§'/9473355, l='MpServer', x=1029.44, y=18.00, z=-5146.35], EntityOtherPlayerMP['§'/9503001, l='MpServer', x=1058.38, y=18.00, z=-5125.30], EntityOtherPlayerMP['§'/9468918, l='MpServer', x=1048.47, y=18.00, z=-5124.64], EntityOtherPlayerMP['§'/9494643, l='MpServer', x=1039.00, y=18.00, z=-5169.00], EntityOtherPlayerMP['§'/9503448, l='MpServer', x=1034.50, y=18.00, z=-5119.50], EntityOtherPlayerMP['§'/9472757, l='MpServer', x=1025.62, y=18.00, z=-5122.88], EntityOtherPlayerMP['§'/9501991, l='MpServer', x=1021.50, y=18.00, z=-5148.50], EntityOtherPlayerMP['§'/9503057, l='MpServer', x=1016.00, y=18.00, z=-5128.00], EntityOtherPlayerMP['§'/9503059, l='MpServer', x=1016.00, y=18.00, z=-5140.00], EntityOtherPlayerMP['§'/9469648, l='MpServer', x=1032.70, y=18.00, z=-5116.30], EntityOtherPlayerMP['§'/9503735, l='MpServer', x=1023.50, y=18.00, z=-5125.50], EntityOtherPlayerMP['§'/9467819, l='MpServer', x=1045.09, y=15.50, z=-5178.07], EntityOtherPlayerMP['§'/9481282, l='MpServer', x=1070.68, y=1.61, z=-5179.50], EntityOtherPlayerMP['§'/9519966, l='MpServer', x=1077.95, y=2.70, z=-5168.81], EntityOtherPlayerMP['§'/9481280, l='MpServer', x=1072.25, y=2.80, z=-5175.24], EntityOtherPlayerMP['§'/9467817, l='MpServer', x=1040.82, y=18.00, z=-5167.95], EntityOtherPlayerMP['§'/9481278, l='MpServer', x=1064.21, y=1.89, z=-5179.21], EntityOtherPlayerMP['§'/9481651, l='MpServer', x=1080.00, y=13.00, z=-5183.00], EntityOtherPlayerMP['§'/9529169, l='MpServer', x=1097.22, y=13.00, z=-5184.67], EntityOtherPlayerMP['§'/9530140, l='MpServer', x=1092.50, y=13.00, z=-5174.50], EntityOtherPlayerMP['§'/9530502, l='MpServer', x=1085.98, y=13.00, z=-5186.17], EntityOtherPlayerMP['§'/9529167, l='MpServer', x=1087.70, y=13.00, z=-5202.27], EntityOtherPlayerMP['§'/9470092, l='MpServer', x=1082.79, y=2.70, z=-5113.48], EntityOtherPlayerMP['§'/9520209, l='MpServer', x=1105.00, y=13.00, z=-5110.00], EntityOtherPlayerMP['§'/9520207, l='MpServer', x=1105.00, y=13.00, z=-5158.00], EntityOtherPlayerMP['§'/9540286, l='MpServer', x=1087.02, y=13.04, z=-5167.30], EntityOtherPlayerMP['§'/9540288, l='MpServer', x=1089.61, y=14.00, z=-5166.21], EntityOtherPlayerMP['§'/9540284, l='MpServer', x=1092.66, y=20.00, z=-5199.77], EntityOtherPlayerMP['§'/9542757, l='MpServer', x=1104.60, y=13.00, z=-5193.18], EntityOtherPlayerMP['§'/9520100, l='MpServer', x=1104.67, y=13.00, z=-5140.87]]
  Chunk stats: MultiplayerChunkCache: 4345, 4345
  Level seed: 0
  Level generator: ID 01 - flat, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (1383,13,-5088), Chunk: (at 7,0,0 in 86,-318; contains blocks 1376,0,-5088 to 1391,255,-5073), Region: (2,-10; contains chunks 64,-320 to 95,-289, blocks 1024,0,-5120 to 1535,255,-4609)
  Level time: 5594021324 game time, 76882540 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
  Level game mode: Game mode: adventure (ID 2). Hardcore: false. Cheats: false
  Forced entities: 4249 total; [I CUT A BUNCH OF STUFF OUT HERE, IT WAS OVER 100k CHARS]
  Server brand: Waterfall <- Wynn
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_361, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 141946288 bytes (135 MB) / 1730150400 bytes (1650 MB) up to 3817865216 bytes (3641 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_G5 13 mods loaded, 13 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                | Version        | Source                                      | Signature                                |
       |:------ |:----------------- |:-------------- |:------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft         | 1.12.2         | minecraft.jar                               | None                                     |
       | LCHIJA | mcp               | 9.42           | minecraft.jar                               | None                                     |
       | LCHIJA | FML               | 8.0.99.99      | forge-1.12.2-14.23.5.2859-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge             | 14.23.5.2859   | forge-1.12.2-14.23.5.2859-universal.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | ColorUtility      | 1.0.4          | minecraft.jar                               | None                                     |
       | LCHIJA | foamfixcore       | 7.7.4          | minecraft.jar                               | None                                     |
       | LCHIJA | foamfix           | 0.10.14-1.12.2 | foamfix-0.10.14-1.12.2.jar                  | None                                     |
       | LCHIJA | deeznuts          | 1.0            | RealFakeMorbMode.jar                        | None                                     |
       | LCHIJA | vanillafix        | 1.0.10-150     | VanillaFix-1.0.10-150.jar                   | None                                     |
       | LCHIJA | wynnvp            | 1.2            | VoicesOfWynnMC1.12.2v1.2.jar                | None                                     |
       | LCHIJA | wi-zoom           | 1.0            | wi-zoom-v1.1-MC1.12.2-release.jar           | None                                     |
       | LCHIJA | wynntils          | 1.14.1         | Wynntils-MC1.12.2-v1.14.1-beta.7.jar        | None                                     |
       | LCHIJA | phosphor-lighting | 1.12.2-0.2.7   | phosphor-forge-mc1.12.2-0.2.7-universal.jar | None                                     |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      WiZoomCoreMod (wi-zoom-v1.1-MC1.12.2-release.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
                                        
                                      ColorUtilityCorePlugin (ColorUtility-universal-1.0.4.jar)
                                        com.Axeryok.ColorUtility.ColorUtilityTransformer
  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.0 Compatibility Profile Context 22.11.2.221130' Renderer: 'Radeon RX 570 Series'
  Wynntils Details: Running Wynntils v1.14.1 in CUTTING_EDGE, at a normal env
  Suspected Mods: Wynntils (wynntils)
  Launched Version: 1.12.2
  LWJGL: 2.9.4
  OpenGL: Radeon RX 570 Series GL version 4.6.0 Compatibility Profile Context 22.11.2.221130, ATI Technologies Inc.
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Wynncraft+Retextured+1.1_for_1.13+.zip (incompatible), Wynnic+Uniques+Compendium-1.0-1.12.2-1.16.zip (incompatible), Wynnic+Vanity+Collection-0.4-1.12.2-1.16.zip (incompatible)
  Current Language: English (United Kingdom)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

### Installed Mods

Prism launcher (multimc fork. does that count? it uses modified version of vanilla)
vanillafix
optifine
liteloader (was not turned on)
foamfix
colorutility (absolutely zero possible interference)
voices of wynn
wi-zoom (optifine zoom but better)
phosphor (lighting)

**Comment by Zffu** [comment]
i think its because the code is trying to access the slot 50 while the max slot is 46.

**Comment by EnderNon** [comment]
> i think its because the code is trying to access the slot 50 while the max slot is 46.

You know, that fully makes sense
but why would there be 46 inventory slots?
